## Librerias

In [36]:
import numpy as np
import sympy as sym

## Problema 2

Considere una cadena larga de resistencias como se muestra en la figura:

![](https://raw.githubusercontent.com/diegour1/CompMetodosComputacionales/main/DataFiles/image8.png)

Todos los resitores tienen las misma resistencia $R$. El voltage en la parte superior izquierda del sistema es $V_+ = 5 \text{V}$. El problema consiste en obtener los voltajes $V_1, \ldots, V_N$ de los puntos internos del circuito. 



a) Usando la ley de Ohm y la ley de corrientes de Kirchoff, la cual dice que la corriente total que fluye hacia afuera o hacia adentro de cada nodo del circuito es cero. Explique porqué los voltajes $V_1, \ldots, V_N$ cumplen con las siguientes ecuaciones.

$$3V_1 − V_2 − V_3 = V_+$$
$$− V_1 + 4V_2 − V_3 − V_4 = V_+,$$
$$\vdots$$
$$− V_{i − 2} − V_{i − 1} + 4V_i − V_{i + 1} − V_{i + 2} = 0,$$
$$\vdots$$
$$− V_{N − 3} − V_{N − 2}+ 4V_{N − 1} − V_N = 0,$$
$$− V_{N − 2} − V_{N − 1} + 3V_N = 0.$$

Pista: Para resolver esta pregunta se usa la ley de Ohm y la ley de corrientes de Kirchhoff. La cual dice que la corriente que fluye hacia adentro o hacia afuera de cada unión del circuito es cero. Por ejemplo para el voltaje $V_1$ se tiene que, 

$$
\frac{V_1-V_2}{R} + \frac{V_1-V_3}{R} + 
\frac{V_1-V_+}{R} = 0, 
$$

Tu explicación aquí

**R/** Usando la ley de corrientes de Kirchoff y la ley de ohm se puede despejar para obtener dicha expresión. Como es independiente de R podemos enfocarnos en únicamente los numeradores.

$$ V_1 - V_2 + V_1 -V_3 + V_1 -V_+ = 0 \rightarrow 3V_1 - V_2 - V_3 = V_+ $$

Y dicha expresión se puede generalizar dada la recurrencia de los voltajes ya que la relación entre ellos siempre será constante,

$$− V_{i − 2} − V_{i − 1} + 4V_i − V_{i + 1} − V_{i + 2} = 0,$$

Donde i será el número de la resistencia dada su ubicación en la figura y V_0 se interpreta como la inicial o en este caso V_+.

b) Escriba las ecuaciones de la forma $A\vec{x} = \vec{b}$ encuentre los valores de la matriz $A$ y del vector $\vec{b}$, para $N=6$. Imprima estos dos resultados en el notebook.



In [30]:
A = np.zeros((6, 6))
b = np.zeros(6)

# Tu codigo aqui
A = np.array([[3.,-1.,-1.,0.,0.,0.], [-1.,4.,-1.,-1.,0,0.], [-1.,-1.,4.,-1.,-1.,0.],[0.,-1.,-1.,4.,-1.,-1.],[0.,0.,-1.,-1.,4.,-1.],[0.,0.,0.,-1.,-1.,3.]])
b = np.array([5.,5.,0.,0.,0.,0.])
# Codigo para la verificacion (no modificar)
print(A)
print(b)

[[ 3. -1. -1.  0.  0.  0.]
 [-1.  4. -1. -1.  0.  0.]
 [-1. -1.  4. -1. -1.  0.]
 [ 0. -1. -1.  4. -1. -1.]
 [ 0.  0. -1. -1.  4. -1.]
 [ 0.  0.  0. -1. -1.  3.]]
[5. 5. 0. 0. 0. 0.]


c) Escriba un programa que resuelva los valores de $V_i$ cuando $N=6$ es decir 6 nodos internos. Guarde e imprima los valores en el vector $\vec{x}$.



In [39]:
x0 = np.array([0.,0.,0.,0.,0.,0.])

# tu codigo aqui
def Jacobi(A,b,x0, itmax=1000, tolerancia= 1e-9):
    
    x = x0.copy()
    
    for it in range(itmax):
        
        xn = np.zeros_like(x0)
        
        for i in range(A.shape[0]):
            
            sum_ = 0.
            
            for j in range(A.shape[1]):
                
                if j!=i:
                    sum_ += A[i,j]*x[j]
                    
            xn[i] = (b[i] - sum_)/A[i,i]
            
        #print(it,xn)
        
        residuo = np.linalg.norm( np.dot(A,xn) - b )
        x = xn.copy()
        #print(residuo)
        
        if np.allclose(residuo,tolerancia,atol=tolerancia):
            break
        
    return x
  
solucion = Jacobi(A,b,x0)
print(solucion)


[3.72549019 3.43137255 2.74509804 2.25490196 1.56862745 1.2745098 ]


d) Encuentre la resistencia total $R_{(N=6)} = \alpha R$, para la red $N=6$, donde $\alpha$ es una constante, imprima el valor de $\alpha$.

In [46]:

# Tu codigo aquí
I = 0

for i in range(0,2):
    I += (5 - solucion[i])
    
alpha = 5 / I


# Codigo para la verificacion (no modificar)
print(alpha)

1.7586206881996955


e) Explique qué haría usted para resolver la resistencia equivalente del circuito para un número infinito de nodos. 

**R/** Como la resistencia total es la suma ponderada de la corriente sobre el voltaje individual, se modificaría el código para que genere las matrices de voltajes infinitos y de ahí, se calcularía la resistencia total. Aunque para un R infinito el denominador de la ecuación de la resistencia se haría los suficientemente grande para que la resistencia total se haga cero.